### ISSUE TITLE
Random location

### ISSUE THREAD

**Issue by hoahong82hh** [Snawoot/windscribe-proxy#19]
Can choose random location each time start docker? Please help me

**Comment by Snawoot** [comment]
Hi!

You can wrap docker invocation into some script to list available locations, select one random and run docker again with selected randomly location. Or you can add such feature into application itself, forking it and implementing feature on your own.

From my side I don't plan such feature because random location doesn't make much sense for normal usage scenario: it doesn't make sense for a user to forward their traffic over random continent, needlessly spoiling latency and throughput.
